version: "3"
services:

  # Веб-визуализатор расположения сервисов по узлам
  viz:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: [ node.role == manager ]


  proxy:
    image: 'jc21/nginx-proxy-manager'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    ports:
      - '81:80'
      - '443:443'
    volumes:
      - ./proxy:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
    networks:
      - mongo-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
      placement:
        constraints: [ node.role == manager ]

networks:
  mongo-net:
    external: true