version: "3"
services:

  # Веб-визуализатор расположения сервисов по узлам
  viz:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8080:8080"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
      placement:
        constraints: [ node.role == manager ]


  # Менеджер управления mongodb
  mongoexpress:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-net
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://rep_mongo1:27017
      ME_CONFIG_BASICAUTH_USERNAME: su
      ME_CONFIG_BASICAUTH_PASSWORD: 1234
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1

networks:
  mongo-net:
    external: true